### ISSUE TITLE
Can i make pr to add ElderGuardian onJoinEvent?

### ISSUE THREAD

**Issue by armagadon159753** [PotatoeTrainYT/PotatoeCore#1]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PotatoeCore
- * [ ] Provide any crash dumps or errors

#### **Steps to Reproduce the Issue**

1.

**Comment by PotatoeTrainYT** [comment]
yeah sure go ahead
