### ISSUE TITLE
Can I

### ISSUE THREAD

**Issue by Metrix187** [PotatoeTrainYT/PotatoeCore#10]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PotatoeCore
- * [ ] Provide any crash dumps or errors

#### **Steps to Reproduce the Issue**

1. It's a Question

#### **Extra Information**

Can I change the name and config.yml so I can say I made it? -Ye Boi

**Comment by PotatoeTrainYT** [comment]
do whatever u like its a template type thing
