### ISSUE TITLE
Want Permission

### ISSUE THREAD

**Issue by BarnesDev** [PotatoeTrainYT/PotatoeCore#3]
Hey PotatoeTrainYT, I was wondering if I could use what you did in the Core.php. What I mean is the perms, ranks, and BaseCommand.php. If it's not okay with you I won't even try. I'm asking this because I'm trying to make my own server Core. The ColdIce Core. ColdIce is a server I'm coming up with. May I join your team of devs, if you have a team.

**Comment by PotatoeTrainYT** [comment]
You can edit what ever you like, and i dont have a devs team sorry

**Comment by BarnesDev** [comment]
ok thx
